### ISSUE TITLE
Show new avatar after uploading

### ISSUE THREAD

**Issue by nikochiko** [hyperlog/hyperlog#19]
The avatar in showcase doesn't update when new file is uploaded. This led me to doubt if my file was actually uploaded successfully. Adding this (like it happens for project image) will be more intuitive.

**Comment by BrainBuzzer** [comment]
I think I had solved this. I'm not sure what exactly you're referring to here.

**Comment by nikochiko** [comment]
It doesnt show a preview of the new avatar (still only shows the old
avatar) after uploading the image and before hitting update.

I made a new pull of main today and it didnt seem to refresh. Maybe the fix
is on another branch and went unmerged?

**Comment by nikochiko** [comment]
My bad. I just saw it in action. It didn't render for me in the morning for some reason.
