### ISSUE TITLE
Signing in with GitHub requires user to authorize read **and write** access to all public repository data?

### ISSUE THREAD

**Issue by zenflow** [hyperlog/hyperlog#31]
![image](https://user-images.githubusercontent.com/3198597/115167847-eac87680-a086-11eb-99d5-a434b008ef05.png)

Why do you need the write access?

It's unfortunate because I want to sign up but I won't authorize the app to take full control of my public repos, when it seems completely unnecessary.

**Comment by nikochiko** [comment]
@zenflow Thanks for pointing this out. It was a simple oversight from our end that we won't need any special permissions for accessing public repositories. Nice catch! :smile:

**Comment by zenflow** [comment]
@nikochiko Amazing! Thanks for the quick fix! Much better now, and I'm excited to explore the product! :D

**Comment by zenflow** [comment]
@nikochiko Oh, I guess I'll have to wait a bit longer since the product is still in closed beta. I signed up on the waitlist though!

p.s. Any chance I could get early access? :D I love to give feedback ;)

**Comment by nikochiko** [comment]
@zenflow Awesome! I love that. I have sent you the invite, and will follow it up with another email. Looking forward to hearing from you :smile:
